### ISSUE TITLE
Archived & Deleted for Wiki & Contact

### ISSUE THREAD

**Issue by cblp** [ff-notes/ff#147]
Do all status-type combinations have meaning?

**Comment by willbasky** [comment]
Contacts has archived Status

**Comment by willbasky** [comment]
Contact type has `Status` field already.
```
struct_set Contact
    #haskell {field_prefix "contact_"}
    status  Status  #ron{merge LWW}
    name    RgaString)
```

Wiki hasn't. 
And they both have deletion (`cmdDeleteContact` and `cmdDeleteNote` for wiki). 
So, this task is just to make wiki status?

**Comment by cblp** [comment]
Wiki is deleted by removing note_status, Archived is not needed. Closing.
