### ISSUE TITLE
Do not use git repo as a database if there is no .ff yet

### ISSUE THREAD

**Issue by cblp** [ff-notes/ff#171]

**Comment by willbasky** [comment]
What the problem with it?

**Comment by cblp** [comment]
The problem: when I'm inside a git repository but don't remember that `.git` exists somewhere, and I want to add a task to my personal repository, I want to type just `ff new ...`. But currently, given such command, ff initializes its own repository `.ff` in the git one silently.

It would be better to show an error in such case or at least silently use an existing `.ff` only without creating a new one.
