### ISSUE TITLE
Add shell completion

### ISSUE THREAD

**Issue by wiz** [ff-notes/ff#6]
Those IDs aren't gonna type themselves...

**Comment by cblp** [comment]
Until completion is done, use copy-paste, bro.

**Comment by cblp** [comment]
I think search must be more useful for selecting notes.

**Comment by willbasky** [comment]
[resolved](https://github.com/ff-notes/ff/pull/94)

**Comment by cblp** [comment]
@wiz is it what you need? if no, open another issue with more details
