### ISSUE TITLE
Add Wiki

### ISSUE THREAD

**Issue by cblp** [ff-notes/ff#88]
1. new status `Wiki`
1. `add` adds task
1. `add --wiki` adds wiki
1. `edit` works with both
1. `agenda` doesn't list wikis

**Comment by willbasky** [comment]
По ключу `--wiki` у ряда функций (например, у `add`) включается функционал работы с вики.
Вики — это заметка с заголовком и текстовым телом, без статуса, дат и других полей.

**Comment by willbasky** [comment]
> agenda doesn't list wikis

How will user know there are wiki notes?

**Comment by cblp** [comment]
> How will user know there are wiki notes?

https://github.com/ff-notes/ff/issues/91
